// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iqqbudpkqkjzkbvkdyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcWJ1ZHBrcWtqemtidmtkeXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTI2NTgsImV4cCI6MjA3MTE4ODY1OH0.jf2g7oTu6MWAmef9DqtIxnIkgtDCj3wEnfmttn1PeZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});